version: '3.8'
services:
  movie-night-frontend:
    image: ${DOCKER_REGISTRY_URL}/${FRONTEND_TAG_NAME}
    ports:
      - "81:80"
      - "444:443"
    environment:
      - NODE_ENV=production
      - BACKEND_PORT=5000
    networks:
      - movie-night-network

  movie-night-backend:
    image: ${DOCKER_REGISTRY_URL}/${BACKEND_TAG_NAME}
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MYSQL_HOST=movie-night-mysql
      - MYSQL_USER=movie_night_user
      - MYSQL_DATABASE=movie_night_db
      - MYSQL_PASSWORD=${MOVIE_NIGHT_MYSQL_PASSWORD}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - EMAIL_FROM=automation@hexd.space
      - EMAIL_NOTIFICATION_TO=${PRIVATE_EMAIL_ADDRESS}
    networks:
      - movie-night-network

  movie-night-mysql:
    image: mysql:8.0
    container_name: movie-night-mysql
    environment:
      - MYSQL_USER=movie_night_user
      - MYSQL_DATABASE=movie_night_db
      - MYSQL_PASSWORD=${MOVIE_NIGHT_MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MOVIE_NIGHT_MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - movie-night-network

networks:
  movie-night-network:
    driver: bridge

volumes:
  mysql_data:

