version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
